# Generated by Django 3.0.6 on 2020-05-17 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.Task'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
