# Generated by Django 3.0.6 on 2020-05-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200517_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='all_done',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='TaskItem',
        ),
    ]
