# Generated by Django 3.0.6 on 2020-05-18 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_root_pk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='all_done',
            new_name='subtasks_done',
        ),
    ]
